# Generated by Django 3.2.4 on 2021-08-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=30)),
                ('vendor_id', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, choices=[('dhaka', 'Dhaka'), ('chattogram', 'Chattogram'), ('rajshahi', 'Rajshahi'), ('barishal', 'Barishal'), ('khulna', 'Khulna'), ('rangpur', 'Rangpur'), ('mymensingh', 'Mymensingh'), ('sylhet', 'Sylhet')], default='dhaka', max_length=20, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('license_no', models.CharField(blank=True, max_length=50, null=True)),
                ('seller_permit', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=30, null=True)),
                ('point_of_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('instagram', models.CharField(blank=True, max_length=30, null=True)),
                ('credit_allowance', models.CharField(blank=True, max_length=6, null=True)),
                ('collection', models.BooleanField(blank=True, default=True, null=True)),
                ('outstanding_credit', models.CharField(blank=True, max_length=100, null=True)),
                ('last_order', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
