# Generated by Django 3.2.4 on 2021-08-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0003_scheduleeducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('product_location', models.TextField(blank=True, null=True)),
                ('brand_exposure', models.BooleanField(blank=True, default=True, null=True)),
                ('product_visibility', models.BooleanField(blank=True, default=True, null=True)),
                ('acc_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_create_report', to='account_management.accountvendor')),
            ],
        ),
    ]
