# Generated by Django 3.2.4 on 2021-08-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0005_createmerchandise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmerchandise',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
