# Generated by Django 3.2.4 on 2021-08-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0011_alter_scheduleeducation_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMerchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_time', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], default='morning', max_length=20, null=True)),
            ],
        ),
    ]
