# Generated by Django 3.2.4 on 2021-08-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0012_ordermerchandise'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermerchandise',
            name='acc_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_av', to='account_management.accountvendor'),
        ),
        migrations.AddField(
            model_name='ordermerchandise',
            name='cm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_cm', to='account_management.createmerchandise'),
        ),
    ]
