# Generated by Django 3.2.4 on 2021-09-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0013_auto_20210811_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(blank=True, max_length=200, null=True)),
                ('product_type', models.CharField(blank=True, max_length=200, null=True)),
                ('flower_type', models.CharField(blank=True, max_length=200, null=True)),
                ('grow_method', models.CharField(blank=True, max_length=200, null=True)),
                ('nutrients_used', models.TextField(blank=True, null=True)),
                ('trim_method', models.CharField(blank=True, max_length=200, null=True)),
                ('curing_time', models.CharField(blank=True, max_length=200, null=True)),
                ('growing_location', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_headquarters', models.CharField(blank=True, max_length=200, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('point_of_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_history_and_mission', models.CharField(blank=True, max_length=200, null=True)),
                ('flower_quality', models.CharField(blank=True, max_length=200, null=True)),
                ('price_point', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
