# Generated by Django 3.2.4 on 2021-09-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0014_custominfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvendor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
