# Generated by Django 3.1.2 on 2021-06-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('position', models.CharField(blank=True, max_length=25, null=True)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_power', models.CharField(blank=True, max_length=6, null=True)),
                ('credit_allowance', models.CharField(blank=True, max_length=6, null=True)),
                ('commission', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, choices=[('dhaka', 'Dhaka'), ('chattogram', 'Chattogram'), ('rajshahi', 'Rajshahi'), ('barishal', 'Barishal'), ('khulna', 'Khulna'), ('rangpur', 'Rangpur'), ('mymensingh', 'Mymensingh'), ('sylhet', 'Sylhet')], default='dhaka', max_length=20, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('license_no', models.CharField(blank=True, max_length=50, null=True)),
                ('seller_permit', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=30, null=True)),
                ('point_of_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('instagram', models.CharField(blank=True, max_length=30, null=True)),
                ('credit_allowance', models.CharField(blank=True, max_length=6, null=True)),
                ('collection', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
