# Generated by Django 3.2.4 on 2021-07-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('metre_uid', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('package_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('price_per_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('strain', models.CharField(blank=True, max_length=30, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('weight_type', models.CharField(blank=True, choices=[('ounce', 'Ounce'), ('pound', 'Pound'), ('gram', 'Gram'), ('kg', 'Kilogram')], default='pound', max_length=20, null=True)),
                ('packaging', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('type_option', models.CharField(blank=True, max_length=30, null=True)),
                ('strain', models.CharField(blank=True, max_length=30, null=True)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('weight_type', models.CharField(blank=True, choices=[('ounce', 'Ounce'), ('pound', 'Pound'), ('gram', 'Gram'), ('kg', 'Kilogram')], default='pound', max_length=20, null=True)),
                ('packaging', models.CharField(blank=True, max_length=20, null=True)),
                ('price_per_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('metre_uid', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity_per_case', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
