# Generated by Django 3.2.4 on 2021-07-03 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210703_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('metric_uid', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availableInventory_incomingInventory', to='employee.availableinventory')),
            ],
        ),
    ]
