# Generated by Django 3.2.4 on 2021-07-10 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_incominginventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('order', models.CharField(blank=True, max_length=10, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('price_per_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('excise_text', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=20, null=True)),
                ('payment_pickup_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('available_vendor_credit', models.CharField(blank=True, max_length=10, null=True)),
                ('vendor_credit_used_today', models.CharField(blank=True, max_length=10, null=True)),
                ('available_employee_credit', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_credit_used_today', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_discount', models.CharField(blank=True, max_length=10, null=True)),
                ('sub_total', models.CharField(blank=True, max_length=10, null=True)),
                ('total_taxes', models.CharField(blank=True, max_length=10, null=True)),
                ('total', models.CharField(blank=True, max_length=10, null=True)),
                ('total_due_today', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_order', to='employee.employees')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_order', to='employee.inventory')),
                ('vendor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_order', to='employee.vendor')),
            ],
        ),
    ]
